#!/bin/sh

# Usage: build has_native has_tgls has_jsoo

set -e 
LOC=`dirname $0`

. $LOC/pkg-builder

NATIVE=$1
TGLS=$2
JSOO=$3

add lib pkg/META		
add lib src/lit.mli
add lib src/lit.cmti	
add lib src/lit.cmi
add lib src/lit.cmx
add lib src/lit.cma
add lib src/lit.a
add lib src/lit.cmxa
add lib src/lit.cmxs

add lib src/litu.mli
add lib src/litu.cmti	
add lib src/litu.cmi
add lib src/litu.cmx
add lib src/litu.cma
add lib src/litu.a
add lib src/litu.cmxa
add lib src/litu.cmxs

if [ "$TGLS" != "false" ]; then
    add lib src/lit_gl3.mli
    add lib src/lit_gl3.cmti
    add lib src/lit_gl3.cmi
    add lib src/lit_gl3.cmx	
    add lib src/lit_gl3.cma
    add lib src/lit_gl3.a
    add lib src/lit_gl3.cmxa
    add lib src/lit_gl3.cmxs

    add lib src/lit_gl4.mli
    add lib src/lit_gl4.cmti
    add lib src/lit_gl4.cmi
    add lib src/lit_gl4.cmx	
    add lib src/lit_gl4.cma
    add lib src/lit_gl4.a
    add lib src/lit_gl4.cmxa
    add lib src/lit_gl4.cmxs

    add lib src/lit_gles2.mli
    add lib src/lit_gles2.cmti
    add lib src/lit_gles2.cmi
    add lib src/lit_gles2.cmx	
    add lib src/lit_gles2.cma
    add lib src/lit_gles2.a
    add lib src/lit_gles2.cmxa
    add lib src/lit_gles2.cmxs
fi

if [ "$JSOO" != "false" ]; then 
    add lib src/lit_webgl.mli
    add lib src/lit_webgl.cmti
    add lib src/lit_webgl.cmi
    add lib src/lit_webgl.cmx	
    add lib src/lit_webgl.cma
    add lib src/lit_webgl.a
    add lib src/lit_webgl.cmxa
    add lib src/lit_webgl.cmxs
fi

add doc README.md
add doc CHANGES.md

build
install lit
